project:
  type: website

pagetitle: "{{< meta title >}} | Adam Pollack"
author-meta: "Adam Pollack"

website:
  title: "Adam Pollack"
  site-url: "https://abpoll.github.io"
  repo-url: "https://github.com/abpoll/abpoll.github.io/tree/quarto"

  navbar:
    pinned: true

    left:
      - text: About
        href: index.qmd
      - text: Now
        href: now.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd

    right:
      - text: '<a class="icon-link" href="mailto:adam-pollack@uiowa.edu" title="E-mail" aria-label="E-mail"><i class="fa fa-envelope" aria-hidden="true"></i></a>'
        href: 'mailto:adam-pollack@uiowa.edu'
      - text: '<a class="icon-link" href="https://github.com/abpoll" title="GitHub" aria-label="GitHub" rel="me"><i class="fa fa-github" aria-hidden="true"></i></a>'
        href: 'https://github.com/abpoll'
      - text: '<a class="icon-link" href="https://scholar.google.com/citations?user=mnigw6AAAAAJ&hl=en&oi=ao" title="Google Scholar" aria-label="Google Scholar"><i class="fa fa-graduation-cap" aria-hidden="true"></i></a>'
        href: 'https://scholar.google.com/citations?user=mnigw6AAAAAJ&hl=en&oi=ao'
      - text: '<a class="icon-link" href="https://www.researchgate.net/profile/Adam-Pollack-4" title="ResearchGate" aria-label="ResearchGate"><i class="fa fa-network-wired" aria-hidden="true"></i></a>'
        href: 'https://www.researchgate.net/profile/Adam-Pollack-4'
      - text: '<a class="icon-link" href="https://orcid.org/0000-0001-6642-0591" title="ORCID" aria-label="ORCID"><i class="fa fa-id-badge" aria-hidden="true"></i></a>'
        href: 'https://orcid.org/0000-0001-6642-0591'

format:
  html:
    theme: [flatly, styles/custom.scc]
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    smooth-scroll: true


bibliography: bibliography/my-papers.bib

freeze: true


